### ISSUE TITLE
Deafen, Mute, and Settings are black and Status Picker has weird spacing. Also, Buttons don't have spacing either.

### ISSUE THREAD

**Issue by Godz-hi** [NYRI4/Comfy-theme#1]
I'm on betterdiscord. Title and picture explains it.
![Discord_9gGYQzBhJA](https://user-images.githubusercontent.com/53191186/102721917-bbb61a00-42cb-11eb-86e1-64501eab9c74.png)

**Comment by NYRI4** [comment]
Hey @Godz-hi, sorry for the late response, if you have not already done so, you need to update the comfy.theme.css

**Comment by Godz-hi** [comment]
No worries! Just updated theme file and everything looks good. Thanks!
