### ISSUE TITLE
"New" Notification clips into game activity

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#11]
I suggest making the "New" notification go above the game activity, when there is game activity; and making the notification stay at the bottom when there is nothing there.

![image](https://user-images.githubusercontent.com/61527626/104237094-6671b200-540c-11eb-99f0-ae2f0dd3d8ef.png)
![image](https://user-images.githubusercontent.com/61527626/104237117-712c4700-540c-11eb-9a6c-694921989386.png)

**Comment by NYRI4** [comment]
How did you do that ?

**Comment by patrickh39** [comment]
First, you start playing a game for game activity and then you have a server near the bottom of the list message / ping everyone

after it should clip into the game activity

**Comment by NYRI4** [comment]
![image](https://user-images.githubusercontent.com/65369563/104629442-cfba2500-5699-11eb-9920-dbe4066d5347.png)
Fixed, I added Wumpus.

**Comment by patrickh39** [comment]
There is now a big black square, like in issue #6

**Comment by NYRI4** [comment]
This should be fixed now, I hope ? (cause it's working for me)

**Comment by patrickh39** [comment]
It's still there, but instead of it having no function, clicking it will trigger the menu where you set your status and presence.

**Comment by NYRI4** [comment]
You need to update your (comfy.theme.css)[https://betterdiscord.net/ghdl?id=3430] and reload your client
