### ISSUE TITLE
Suggestion for activities. (Black box when not listening to music or playing games)

### ISSUE THREAD

**Issue by Godz-hi** [NYRI4/Comfy-theme#13]
Ok so I've been messing around a bit with the activities. Here's a little experimental file I have: https://raw.githubusercontent.com/Godz-hi/Comfy-theme/main/src/main.css

 Quick run down of what I did:
-  Made the server list's bottom margin smaller. 
- I moved the game and Spotify presences down like 5 pixels
- I then made Spotify's presence 6 on the z-index and 5 for game presences. (To keep Spotify on top even when playing a game.)
- I think that's it!

So now whenever you aren't listening to music or playing a game nothing is there but when you are it will show on top of server lists.

Bugs with it: 

1. Notifications are on top of presence; easy fix just don't want to ruin the style of the theme
2. No border on the top of the presence so it kinda just cuts into the server list which in my opinion doesn't look the best. (I didn't know how to go about adding a border without it being in animation as well, so that's why I didn't do this)

Lemme know if you think this could be added to the theme I think it makes it look a lot nicer when you aren't listening to music or playing games!

Here's some images: 

With presence:
![image](https://user-images.githubusercontent.com/53191186/104767496-3f7fec80-573a-11eb-99f7-71e1610dbea1.png)

Without presence: 
![image](https://user-images.githubusercontent.com/53191186/104767521-4ad31800-573a-11eb-9703-98f7b774b053.png)

**Comment by Godz-hi** [comment]
Only reason I didn't create a pull request is because this is not ready to be added right out the box it definitely still needs some work.

**Comment by NYRI4** [comment]
You can't put the Spotify presence above the server list because then, you wont be able to scroll all the way down

**Comment by Godz-hi** [comment]
Fixed that issue just had to add some padding updating fork now!

**Comment by Godz-hi** [comment]
Ok so I fixed it just added some padding to the scroller-2TZvBN only thing is there is some extra space at the bottom which isn't a huge downside in my opinion. I'll update images in a sec!

**Comment by NYRI4** [comment]
bruh im so dumb thx

**Comment by NYRI4** [comment]
It should be fixed now, thx again
