### ISSUE TITLE
Notif covers presence.

### ISSUE THREAD

**Issue by Godz-hi** [NYRI4/Comfy-theme#14]
As I mentioned in my transparent presence suggestion I added yesterday the bottom new notification covers it up. I decided not to mess with it since I didn't know how to make it go with the theme in some other place. 
![image](https://user-images.githubusercontent.com/53191186/104821898-1b411000-580d-11eb-8b4c-5ad8ed136f8e.png)
^^^ Picture for reference.

**Comment by Godz-hi** [comment]
Lemme throw together a suggestion I have for the theme, gimme a few.

**Comment by Godz-hi** [comment]
Alright here's my finished idea: 
![image](https://user-images.githubusercontent.com/53191186/104822986-b5f11d00-5814-11eb-8ac1-2b93b7d28a8e.png)

Here's the code:
https://github.com/Godz-hi/Comfy-theme/blob/main/src/main.css

**Comment by NYRI4** [comment]
thx for the idea, I was inspired by it and here's what I just pushed :
![image](https://user-images.githubusercontent.com/65369563/104839077-379d8500-58bf-11eb-8621-cd7010f386a9.png)

**Comment by Godz-hi** [comment]
That looks really good!
