### ISSUE TITLE
Notch for checking ping in VC is green

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#16]
When you hover over the status symbol to show ping, the down arrow in the ms indicator is green and it should match the colour of background.

I drew a red box to highlight.

![image](https://user-images.githubusercontent.com/61527626/104974768-cab4e880-59ad-11eb-8215-4a7c26a23417.png)
![image](https://user-images.githubusercontent.com/61527626/104974983-4b73e480-59ae-11eb-9cd1-3235752871ca.png)

**Comment by NYRI4** [comment]
Fixed
