### ISSUE TITLE
Tooltip when rightclicking on user is too far away from the menu

### ISSUE THREAD

**Issue by marcpinet** [NYRI4/Comfy-theme#19]
This issues itself in this GIF is really annoying. If you aren't fast enough, you might end trying again and again to get those buttons. The tooltip is too far away from the menu I guess.

[Issue1 - gif1](https://i.imgur.com/IcoEwGx.gif)
[Issue1 - gif2](https://i.imgur.com/Mv4xHWy.gif)

**Comment by piotr25691** [comment]
Until this gets fixed by the author of the theme, try this CSS: (enter into custom CSS)
```css
.menu-3sdvDG .layer-v9HyYc {
    margin-left: -10px;
}
```
![obraz](https://user-images.githubusercontent.com/71488561/105855043-eb052880-5fe7-11eb-8d1f-afb608c41bd9.png)

**Comment by NYRI4** [comment]
Fixed
