### ISSUE TITLE
Hovering Menu for Mute/Deafen/Settings was a really bad idea.

### ISSUE THREAD

**Issue by Roux55** [NYRI4/Comfy-theme#2]
Yes, this was a really bad idea since it takes time to shows up (so, for fast people it is a pain to wait for the menu to slides). Furthermore, for those who have the "GameActivityToggle.js" button, the menu overtakes space and it's really ugly.

The theme was cool but this addition made me change theme until it gets fixed.
The only good addition was to move the "Change user status" button at the bottom left and not next to the text area.

![cacademerde](https://user-images.githubusercontent.com/52708150/103476979-8f65c780-4dba-11eb-97f2-d8285dbad036.gif)

**Comment by NYRI4** [comment]
Well
![image](https://user-images.githubusercontent.com/65369563/103481843-93efa780-4ddd-11eb-9d40-0237713cdc56.png)

**Comment by Roux55** [comment]
> Well
> ![image](https://user-images.githubusercontent.com/65369563/103481843-93efa780-4ddd-11eb-9d40-0237713cdc56.png)

Okay so how did you do that basically ?

**Comment by NYRI4** [comment]
I just updated it

**Comment by Roux55** [comment]
> I just updated it

Oh okay nice, thank you for hearing me. 
Have a nice day.
