### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by Godz-hi** [NYRI4/Comfy-theme#3]
![image](https://user-images.githubusercontent.com/53191186/103488999-1af14f80-4ddf-11eb-8ee9-8df9cd7a8bf9.png)
I still have the spacing for where the deafen and mute buttons went. On better discord.

**Comment by zzerexx** [comment]
Spotify presence is supposed to be there. It will occupy the space when you're playing music.
![image](https://user-images.githubusercontent.com/74355984/103525890-d42e4480-4e34-11eb-8dc2-4dc98d883ca1.png)

**Comment by Godz-hi** [comment]
Well I mean shouldn't be there when not listening to music and also when playing doesn't pop up for me. It might be a better discord thing.

**Comment by Godz-hi** [comment]
![Screenshot 2021-01-05 182958](https://user-images.githubusercontent.com/53191186/103710861-0d28ff00-4f84-11eb-98db-3c756673e35f.png)
Ok so I added the spotify plugin for better discord it sort of works but looks really odd.

![image](https://user-images.githubusercontent.com/53191186/103710899-25991980-4f84-11eb-9ae3-c343c118c084.png)
This is when I hover over it bottom spacing looks a little off as well.

**Comment by NYRI4** [comment]
Should be fixed now
