### ISSUE TITLE
Notes of Users Don't Show

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#5]
As the title suggests, the notes you add on a user don't show when you click on a user. They only show when you press view profile.

The profiles were interacted with on a group chat. Not a server. **On a server, the function of notes have completely disappeared.**

![image](https://user-images.githubusercontent.com/61527626/104073209-eb1cc000-51c1-11eb-8827-2524e3ca603f.png)
![image](https://user-images.githubusercontent.com/61527626/104073226-f8d24580-51c1-11eb-86f9-7f0d9ef56c7c.png)

![image](https://user-images.githubusercontent.com/61527626/104073280-1ef7e580-51c2-11eb-9c65-40c3cc80bdae.png)
![image](https://user-images.githubusercontent.com/61527626/104073252-0f789c80-51c2-11eb-8b99-656ab62dc8ab.png)

**Comment by NYRI4** [comment]
Go into your theme folder, open comfy.theme.css and delete the "BetterPopout" part.

**Comment by patrickh39** [comment]
Resolved
