### ISSUE TITLE
Blank Space Above Profile Picture

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#6]
There's a big blank space with nothing above my profile picture and clicking on it repeatedly will make it show a yellow border.

![image](https://user-images.githubusercontent.com/61527626/104073448-8dd53e80-51c2-11eb-91af-7f67bb19eb73.png)
![image](https://user-images.githubusercontent.com/61527626/104073489-a6ddef80-51c2-11eb-9c17-4d2b063719b4.png)

**Comment by NYRI4** [comment]
Should be fixed now

**Comment by patrickh39** [comment]
Resolved

**Comment by patrickh39** [comment]
When there are new messages, the NEW notification still aligns with the old spacing issue.
![image](https://user-images.githubusercontent.com/61527626/104110901-099dbc80-5291-11eb-9c4d-c758506013ef.png)
