### ISSUE TITLE
User Profile Doesn't Show All The Way at Window Border

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#7]
When you reach the border of the window of Discord, and you click on somebody's profile icon, the card will either: clip out of discord, or bump discord up to the point you can actually view the card but not discord anymore. It usually acts like this when somebody has game activity, spotify playing, a long discord custom status, or lots of roles assigned on them. This behaviour is in both DMs, group chats, and servers.

After dismissing the glitch once and clicking on the person's profile picture icon, it will act responsively and fit into the window.

![image](https://user-images.githubusercontent.com/61527626/104083157-3d290a00-51f1-11eb-94b9-0b8c69e7c9f5.png)
![image](https://user-images.githubusercontent.com/61527626/104083329-8cbc0580-51f2-11eb-9d3f-54dd30dd5c5e.png)

**Comment by NYRI4** [comment]
I'm not responsible of that, that's a Discord issue.

**Comment by NYRI4** [comment]
If your using Powercord, here's a fix : https://github.com/cyyynthia/fix-user-popouts
