### ISSUE TITLE
Set a Custom Status Clips with Emoji

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#8]
Maybe make it wider? Not sure..

![image](https://user-images.githubusercontent.com/61527626/104083615-fb9a5e00-51f4-11eb-8496-edeb6dd897f6.png)
![image](https://user-images.githubusercontent.com/61527626/104083627-1371e200-51f5-11eb-9a8c-f401bd6a2a6e.png)

**Comment by NYRI4** [comment]
Should be fixed now

**Comment by patrickh39** [comment]
Resolved.
