### ISSUE TITLE
Long text will clip out of bar if attempted streaming

### ISSUE THREAD

**Issue by patrickh39** [NYRI4/Comfy-theme#9]
![image](https://user-images.githubusercontent.com/61527626/104084783-170a6680-51ff-11eb-8c6f-6c9e679e0dad.png)

**Comment by NYRI4** [comment]
That's Discord problem
![Capture](https://user-images.githubusercontent.com/65369563/104104603-78870f80-52a9-11eb-8b61-3dd31a5c3555.PNG)
